# Generated by Django 4.0.4 on 2022-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR')], default='hr', max_length=70),
        ),
    ]
