# Generated by Django 4.0.4 on 2022-05-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('ENGINEERING', 'ENGINEERING'), ('RESEARCH', 'RESEARCH'), ('MARKETING', 'MARKETING'), ('SALES', 'SALES')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
