# Generated by Django 4.0.4 on 2022-05-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_jobpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='vacancy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
