# Generated by Django 4.0.4 on 2022-05-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_candidateprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
