# Generated by Django 4.0.4 on 2022-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(upload_to='profile/'),
        ),
    ]
